//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlbingiaSiteWebBI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Core.Objects;
    using System.Data.Entity.Infrastructure;

    using System.Linq;
    
    public partial class ALB_APPEntities : DbContext
    {
        public ALB_APPEntities()
            : base("name=ALB_APPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<IND_COLLABORATEUR> IND_COLLABORATEUR { get; set; }
        public DbSet<IND_SUJET> IND_SUJET { get; set; }
        public DbSet<IND_COMPTAGE_TACHE> IND_COMPTAGE_TACHE { get; set; }
    
        public virtual int Mise_A_Jour_Apres_Validation(Nullable<long> iD_COLLAB, Nullable<System.DateTime> dATE_DEBUT)
        {
            var iD_COLLABParameter = iD_COLLAB.HasValue ?
                new ObjectParameter("ID_COLLAB", iD_COLLAB) :
                new ObjectParameter("ID_COLLAB", typeof(long));
    
            var dATE_DEBUTParameter = dATE_DEBUT.HasValue ?
                new ObjectParameter("DATE_DEBUT", dATE_DEBUT) :
                new ObjectParameter("DATE_DEBUT", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Mise_A_Jour_Apres_Validation", iD_COLLABParameter, dATE_DEBUTParameter);
        }
    }
}
