//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlbingiaSiteWebBI
{
    using System;
    using System.Collections.Generic;
    
    public partial class IND_COLLABORATEUR
    {
        public IND_COLLABORATEUR()
        {
            this.IND_COMPTAGE_TACHE = new HashSet<IND_COMPTAGE_TACHE>();
        }
    
        public long COL_ID { get; set; }
        public string COL_BRANCHE { get; set; }
        public string COL_SERVICE { get; set; }
        public string COL_EQUIPE { get; set; }
        public string COL_NOM { get; set; }
        public string COL_PRENOM { get; set; }
        public string COL_ADRESSE_MAIL { get; set; }
        public Nullable<System.DateTime> Loading_Date { get; set; }
        public string COL_LIBELLE_COURT { get; set; }
        public Nullable<int> indicateur { get; set; }
        public Nullable<int> COL_TRI { get; set; }
    
        public virtual ICollection<IND_COMPTAGE_TACHE> IND_COMPTAGE_TACHE { get; set; }
    }
}
