//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlbingiaSiteWebBI
{
    using System;
    using System.Collections.Generic;
    
    public partial class IND_SUJET
    {
        public IND_SUJET()
        {
            this.IND_COMPTAGE_TACHE = new HashSet<IND_COMPTAGE_TACHE>();
        }
    
        public long SUJ_ID { get; set; }
        public string SUJ_LIBELLE { get; set; }
        public string SUJ_BRANCHE { get; set; }
        public Nullable<int> SUJ_TRI { get; set; }
        public Nullable<System.DateTime> Loading_Date { get; set; }
        public string COL_SERVICE { get; set; }
    
        public virtual ICollection<IND_COMPTAGE_TACHE> IND_COMPTAGE_TACHE { get; set; }
    }
}
